- example/example_fbo.c
- src/nanovg_gl_utils.h
The `NVGLUframebuffer` structure contains a `ctx` member but was actually never used. This commit takes advantage of the `ctx` property so there is no need to keep the reference of the context elsewhere after calling `nvgluCreateFramebuffer()`, or it would add difficulty for maintenance. As a result, the `nvgluDeleteFramebuffer()` function only needs to take one `NVGLUframebuffer` instance as the parameter.
> Improve the use of NVGLUframebuffer.

- src/nanovg_gl.h
in some situations int and GLsizei are not the same type which leads to conversion warnings
> fixed type usage

- src/fontstash.h
- src/nanovg.c
Just a few small changes to silence warnings when compiling in Xcode 7.3.1 (llvm 7.3.0).
Note that I'm also using the freetype2 font support, hence the additional #ifdef to silence unused function warnings.
> Fixing clang compiler warnings.

- src/nanovg.c
- src/nanovg.h
- src/nanovg_gl.h
This commit updates the `nvgBeginFrame()` function to forward the received `devicePixelRatio` parameter to the `renderViewport()` function so it is possible to configure the environemnt correctly when using `bgfx` backend.
The current implementation of the `renderViewport()` function in bgfx backend is implemented in this line: https://github.com/bkaradzic/bgfx/blob/7de947c7c08acdc597bc0bd3f67f43e2bafd3760/examples/common/nanovg/nanovg_bgfx.cpp#L553 
However, the `bgfx::setViewRect()` function won't work properly if the passed width and height are not multiplied to the `devicePixelRatio`, and because `devicePixelRatio` is kept in `NVGcontext` and the `NVGcontext` object is only visible in the `nanovg.c` file. It seems that passing the `devicePixelRatio` parameter to the `renderViewport()` …
> Add support for bgfx

- src/nanovg.c
- src/nanovg.h
- src/nanovg_gl.h
This commit implements the `nvgGlobalCompositeOperation()` function to support blending between frames. All operations defined in HTML5 canvas API are supported. Also, it is possible to create custom composite operation by calling `nvgGlobalCompositeBlendFunc()` or `nvgGlobalCompositeBlendFuncSeparate()` functions.
Example:
nvgBeginFrame(ctx, ...);
nvgBeginPath(ctx);
nvgRect(ctx, 20, 20, 75, 50);
nvgFillColor(ctx, nvgRGBf(1, 0, 0));
nvgFill(ctx);
nvgEndFrame(ctx);
nvgBeginFrame(ctx, ...);
nvgGlobalCompositeOperation(ctx, NVG_DESTINATION_OVER);
nvgBeginPath(ctx);
nvgRect(ctx, 50, 50, 75, 50);
nvgFillColor(ctx, nvgRGBf(0, 0, 1));
nvgFill(ctx);
nvgEndFrame(ctx);
> Implements composite operation for blending renderings.

- src/fontstash.h
This commit fixes issue #302 that the kerning value returned by freetype is not converted to integer properly.
> Fixes the kerning value for freetype.

- src/nanovg_gl.h
This commit fixes #300 and #306 that “control may reach end of non-void function” error occurs in `glnvg_convertBlendFuncFactor()`. The function now returns `GL_INVALID_ENUM` for invalid blend factor and if that happens, `glnvg__blendCompositeOperation()` uses default source-over composite operation.
> Fallbacks to default composite operation when invalid one is specified.

- src/nanovg_gl.h
There was no `nvglImageFromHandleGL2` implementation, only declaration, it must have been
an error during some refactoring.
This commit renames `nvglImageFromHandleGL2` to `nvglImageHandleGL2` so now this declaration matches definition at the bottom of the file and is named similarly to other GL* functions with same name
> Rename nvglImageFromHandleGL2 -> nvglImageHandleGL2

- src/nanovg_gl.h
This commit fixes issue #167 that `nvgImagePattern()` does not handle coordinate well if the specified image applies the `NVG_IMAGE_FLIPY` parameter.
> Fixes a bug when applying `NVG_IMAGE_FLIPY`.

- src/nanovg.c
This commit improves to display CJK characters mixed with English words so there is less spaces at line breaks. It seems that the previous commit didn't handle CJK characters very well. This commit should fix the issue.
Before:
After:
> Improves to display CJK characters with English words.

- src/fontstash.h
- src/nanovg.c
This commit fixes the bug that text may not render correctly when glyph is not found in fallback fonts. This bug is hard to find when rendering western letters because almost every font includes all western letters. But when it comes to Chinese characters, it's easily that a glyph is not found in western fonts and `fons__getGlyph()` should return `NULL` until meeting a Chinese font.
Before:
After:
> Fixes the bug that text may not render correctly.

- src/nanovg.c
Previously, the Unicode range of the CJK chractaters only includes Chinese charactaters, Japanese Kanji, and CJK Symbols and Punctuation. The range are used by traditioanl Korean as well. This commit further includes [Hiragana](https://en.wikipedia.org/wiki/Hiragana_(Unicode_block)) and [Katakana](https://en.wikipedia.org/wiki/Katakana_(Unicode_block)) in Japanese, and [Hangul Syllables](https://en.wikipedia.org/wiki/Hangul_Syllables) and [Hangul Jamo](https://en.wikipedia.org/wiki/Hangul_Jamo_(Unicode_block)) in Korean to make CJK support more complete.
Here's a Japanese Example.
Before:
After:
> Better support for CJK characters.

- src/nanovg.c
There are a bunch of warnings reported by Apple LLVM version 8.0.0 (clang-800.0.42.1).  This commit suppresses them,
> suppresses all warnings reported by latest Xcode/AppleClang

- premake4.lua
- src/nanovg_gl.h
I've discovered two bugs which prevented NanoVG from compiling under OS X 12.3 correctly.  First, the Carbon framework was missing, which prevented correct linking as they are needed by GLFW.  Second, I discovered that `nanovg_gl.h` was missing the includes for `<OpenGL/glext.h>`.  I've made both fixes, and put them as separate commits in this pull request.
> Bug fixes to compile under OS X 12.3

- example/example_gl2.c
- example/example_gl3.c
- example/example_gles2.c
- example/example_gles3.c
- src/nanovg_gl.h
This commit fixes the issue caused by #357 that nanovg failed to compile on iOS due to the wrong way of including glext header.
> Fixes how glext header is included.

- src/nanovg_gl.h
This commit moves the `discard` instruction in the fragment shader to an earlier position to avoid performing calculations whose results are unused.
In my real world app, tens of thousands polygons may render per frame, and this simple change improves the FPS from 37 to 45 in a test case. It's not bad.
Before:
After:
> Discards fragments as early as possible.

- src/nanovg.c
- src/nanovg.h
This commit adds `nvgEnable()` and `nvgDisable()` functions for changing flags after creating the `NVGcontext` object.
Allowing changing flags is useful to get some performance gain at certain situations. For example, when applying `nvgFill()` and `nvgStroke()`  to the same path with an opaque stroke color. The antialiasing for fill operation is unnecessary because the shape edge will be covered by stroke anyway. That way, I can do something like the following code to reduce some triangle vertices from processing.
nvgDisable(context, NVG_ANTIALIAS);
nvgFill(context);
nvgEnable(context, NVG_ANTIALIAS);
nvgStroke(context);
In my real world app. I need to stroke and fill thousands of polygons per frame, and this would help improve the FPS and battery consumption a bit. Here's a simple …
> Allows to turn on/off antialias for shapes.

- src/fontstash.h
- src/nanovg.c
A few minor changes to fix compiler warnings in Xcode 8.3.
> Fix clang compiler warnings

- src/nanovg_gl.h
This fixes a compiler warning when using Visual Studio 2017 to compile. 
It warns about the conversion from int to float on the line with the ternary operator determining the textype. 
Textype can be an int or float depending on whether NANOVG_GL_USE_UNIFORMBUFFER is defined.
This takes that into account using the aforementioned define to avoid this warning.
> Fix MSVC 2017 compiler warning

- src/fontstash.h
- src/nanovg.c
When font atlas is full, the `fons__getGlyph()` function simply returns `NULL` and makes a lot of corresponded functions return unreliable results.
For example, when trying to auto scale text’s font size to fit a rectangle. The text may set a large font size initially and repeatedly calling `nvgTextBounds()` and reducing font size until the text can fit well.
This process may create a lot of one-time use font images and quickly makes the atlas full. As a result, `nvgTextBounds()` doesn't return a reliable result anymore because no new glyph can be generated.
This commit implements the error callback to reset the atlas when receiving the `FONS_ATLAS_FULL` error.
> Resets font atlas when it is full.

- src/nanovg_gl.h
This silences a warning in Clang (and GCC?) when -Wall and -Wextra is turned on.
> Mark devicePixelRatio unused in glnvg_renderViewport

- src/nanovg.c
- src/nanovg.h
- src/nanovg_gl.h
This commit changes the type of the view size accepted by `nvgRenderFrame()` from `int` to `float` so it matches the type defined in `GLNVGcontext`. This would prevent a framebuffer missing a pixel in final rendering result.
> Fixes the type of view size.

- src/nanovg.c
This commit fixes #494. I've seen characters missing on iOS and Android couple of times. I'd like to help submitting PR for this fix. Thanks @jlinse.
> Fixes text corruption on atlas rebuild.

- src/fontstash.h
This commit adds the `FT_LOAD_FORCE_AUTOHINT` parameter to `FT_Load_Glyph()` to fix wonky non-alphabetic  characters. 
I found this issue when I tried to display Google's open source Noto CJK font on an Android device. (CJK font combines Chinese, Japanese, and Korean fonts into one file because they all share a lot of Chinese and variant characters.), which is also the default font when setting Android's system language to Chinese.
This picture shows the big difference when adding `FT_LOAD_FORCE_AUTOHINT`. The font displayed on the left looks pretty bad and nothing like the font displayed by Android UI. However, the font displayed on the right looks much nature and matches the font displayed by Android UI.
> Forces autohint when loading glyph using FreeType.

- src/fontstash.h
Fix #377 
32bit platform needs  more buffer size then 64bit platform
https://github.com/memononen/nanovg/blob/master/src/stb_truetype.h#L1617
on 32bit 
`sizeof(stbtt__active_edge) == 28`
count is 2000
on 64bit 
`sizeof(stbtt__active_edge) == 32`
count is 800
> Fix example crash on 32bit platform

- src/nanovg_gl.h
This commit fixes the bug that `glnvg__convexFill()` tried to draw fringes depending on whether `NVG_ANTIALIAS` is set. However, #386 adds `nvgShapeAntiAlias()` for chaning anti-alias state explicitly, and `glnvg__convexFill()` would cause error If the anti-alias state is disabled.
> Fixes the bug that gl may fail to draw fringes.

- src/fontstash.h
This commit fixes the issue that freetype library isn’t released in `fonsDeleteInternal()` and causes memory leaks.
> Fixes memory leaks of freetype.

- src/fontstash.h
master fails to build due to a missing `{` introduced by commit 9b27dc38947a69d2b93c9a3b6b5a707f159e9b2e.
> Fix compile issue for missing { in fontstash.h

- src/fontstash.h
- src/stb_truetype.h
This commit fixes the issue that font size is inconsistent between different font files. `stb_truetype.h` is also updated to the latest version to support additional font types such as OpenType fonts.
The inconsistent font size issue was mentioned at #382 and I experienced the same issue for my app a long time ago. I always see different font sizes (even if they set to the same value) with different font files on screen.
Here is the current NanoVG's implementation result compared to Apple's Pages app. There are three font files used for English / Chinese / Thai, respectively.
* English: Gotham Round (TTF)
* Chinese: Noto Sans CJK (OTF)
* Thai: Noto San Thai (TTF)
The Pages app shows bolder font for some reason, but that doesn't matter. Here we can see the stb backend can't render OpenType …
> Fixes the issue that font size is inconsistent.

- src/fontstash.h
- src/nanovg.c
- src/nanovg.h
This commit allows loading a certain font face from a font collection file such as TTC. 
TTC file is very important for CJK fonts. For example, Android includes `.ttc` font files for CJK characters due to the fact that Chinese/Japanese/Korean share a lot of characters. Without a `.ttc` file, we need four files (each file takes at least 15 MB) to support all of Japanese/Chinese/Korean characters. The Noto-CJK TTC font file included in Android only takes ~25 MB.
Currently, the stb implementation in NanoVG does not support TTC at all as mentioned in #554. And the FreeType implementation only loads the first font face in the TTC. This isn't ideal as the same character may look different in different languages.
Without TTC support, we need to bundle 4 font files to cover all CJK characters, …
> Support for loading a certain font face from a font file.

- src/nanovg.c
- src/nanovg.h
- src/nanovg_gl.h
fixes bad clipping of text on high DPI screens
Here is an example of the results we are getting without this fix, the text is clipped to control bounds with nvgscissor, but if the text goes outside the bounds we get some artifacts at the edges on retina screens. On low-DPI screens there are no such artifacts.
> Pass fringe parameter to renderTriangles

- src/fontstash.h
- src/nanovg.c
- src/nanovg.h
This commit adds `nvgResetFallbackFontsId()` and `nvgResetFallbackFonts()` functions for resetting fallback fonts. This would be very useful for improved CJK font support.
For example. If we always use an English-only font as the base font. We need to make sure the first fallback font is a Japanese font for Japanese articles or a Chinese font for Chinese articles. Right now there is no way to reset fallback fonts and thus the first assigned CJK font will be used across different languages.
> Support for resetting fallback fonts.

- src/fontstash.h
iOS uses the `Hiragino Sans` font as the default Japanese font. However, this font abuses the `line gap` property like many fonts.
* Adobe fonts usually treat `line gap` as the `line height`.
* Most other western fonts sets `line gap` to 200.
Back to the `Hiragino` font. The font family always sets `line gap` to 500 no matter what while the `font height (ascent - descent)` is only 1000. Which causes the spaces between lines are super big. 
As mentioned here https://stackoverflow.com/questions/5414730/custom-installed-font-not-displayed-correctly-in-uilabel, Apple ignores the `line gap` property since iOS 7, and a workaround to fix this issue is to add the `line gap` to the `ascent` and we'll be fine to ignore the `line gap` property. Now the result looks much normal.
This change doesn't …
> Fixes the issue that line gap may ruin the text layout.

- example/demo.c
This commit fixes the demo’s font sizes for the changes in #558, which makes the rendered font size matches what you saw on other native apps. The demo used bigger font sizes than they actually were. This commit deduces the font sizes to match the original demo’s look.
> Fixes demo’s font sizes.

- src/nanovg_gl.h
fixes the WebGL error "RENDER WARNING: there is no texture bound to the unit 0"" in Chrome
note: previous PR worked with nanovg example, but not with iPlug2, where webgl context is initially hidden. In this PR i create the dummy texture on first use which seems to work in both cases
see discussion https://github.com/memononen/nanovg/issues/398#issuecomment-437004233
> Bind a dummy texture in setUniforms when compiling with emscripten

- src/fontstash.h
In Visual Studio 17, I get warnings related to these variables:
````
fontstash.h(241): warning C4018: '<': signed/unsigned mismatch
fontstash.h(242): warning C4018: '<': signed/unsigned mismatch
````
Making them unsigned fixes it.
> Fixed Signed/Unsigned Comparison Warning

- src/fontstash.h
With nanovg as renderer for @rxi's excellent [lite](https://github.com/rxi/lite) code editor, I noticed the following undesirable glyph wonkiness when using FreeType:
The `s` glyph is particularly egregious.
Adding `FT_LOAD_TARGET_LIGHT` to the `FT_Load_Glyph` flags ([see docs](https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_load_target_xxx)) did the trick:
> fix for freetype glyph loading 

- src/nanovg.c
> Fixed text vanishing when the transform is vertically flipped

- src/fontstash.h
This commit fixes the issue mentioned by https://github.com/memononen/nanovg/commit/0b37350df78dbe43844655b4e9cc073ac8a2e102#r63095702
> Fixes stbtt implemention

- src/nanovg.c
This commit fixes the memory leak issue caused by not handling the situation where the number of allocated font images meets `NVG_MAX_FONTIMAGES`.
In this implementation of handling such situation. All existing font images will be released and a new one with the `NVG_MAX_FONTIMAGE_SIZE` will be created.
> Fixes memory leaks caused by full font images.

- src/nanovg.c
Currently, `NVG_MAX_STATES` is set to 32. But it’s not enough sometimes in my case. This commit allows defining the preferred `NVG_MAX_STATES` number.
> Allows setting the `NVG_MAX_STATES` number.
